In [109]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [110]:
from google.colab import files
upload=files.upload()

Saving Bank.csv to Bank (1).csv


In [111]:
Bank= pd.read_csv("Bank.csv", sep=";")

In [128]:
Bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   education  45211 non-null  object
 2   balance    45211 non-null  int64 
 3   duration   45211 non-null  int64 
 4   campaign   45211 non-null  int64 
 5   pdays      45211 non-null  int64 
 6   previous   45211 non-null  int64 
 7   poutcome   45211 non-null  object
 8   y          45211 non-null  object
dtypes: int64(6), object(3)
memory usage: 3.1+ MB


In [129]:

Bank.drop(["education"],inplace=True,axis = 1)
Bank.drop(["y"],inplace=True,axis = 1)
Bank.drop(["poutcome"],inplace=True,axis = 1)

In [130]:
Bank.head(5)

age  balance  duration  campaign  pdays  previous
0   58     2143       261         1     -1         0
1   44       29       151         1     -1         0
2   33        2        76         1     -1         0
3   47     1506        92         1     -1         0
4   33        1       198         1     -1         0

In [131]:
Bank

age  balance  duration  campaign  pdays  previous
0       58     2143       261         1     -1         0
1       44       29       151         1     -1         0
2       33        2        76         1     -1         0
3       47     1506        92         1     -1         0
4       33        1       198         1     -1         0
...    ...      ...       ...       ...    ...       ...
45206   51      825       977         3     -1         0
45207   71     1729       456         2     -1         0
45208   72     5715      1127         5    184         3
45209   57      668       508         4     -1         0
45210   37     2971       361         2    188        11

[45211 rows x 6 columns]

In [132]:

Bank.shape

(45211, 6)

In [133]:
#To check number of missing values?
Bank.isnull().sum()

age         0
balance     0
duration    0
campaign    0
pdays       0
previous    0
dtype: int64

In [134]:
Bank[Bank.isnull().any(axis=1)]

Empty DataFrame
Columns: [age, balance, duration, campaign, pdays, previous]
Index: []

In [135]:
len(Bank[Bank.isnull().any(axis=1)])/1340

0.0

In [136]:
# Removing NA values in data set
Bank = Bank.dropna()
Bank.shape

(45211, 6)

In [137]:
Bank

age  balance  duration  campaign  pdays  previous
0       58     2143       261         1     -1         0
1       44       29       151         1     -1         0
2       33        2        76         1     -1         0
3       47     1506        92         1     -1         0
4       33        1       198         1     -1         0
...    ...      ...       ...       ...    ...       ...
45206   51      825       977         3     -1         0
45207   71     1729       456         2     -1         0
45208   72     5715      1127         5    184         3
45209   57      668       508         4     -1         0
45210   37     2971       361         2    188        11

[45211 rows x 6 columns]

In [138]:
# Dividing our data into input and output variables
X = Bank.iloc[:,1:]
Y = Bank.iloc[:,0]

In [139]:
#Logistic regression and fit the model
classifier = LogisticRegression()
classifier.fit(X,Y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [140]:
classifier.coef_

array([[-1.40272530e-03, -7.26699785e-03, -1.27310617e-04,
        -1.29176034e-03, -1.73602791e-05],
       [-6.67521820e-04, -6.46624585e-03, -1.08675954e-04,
        -1.01267476e-03, -1.42151690e-05],
       [-2.25165408e-04, -5.77889279e-03, -1.16288129e-04,
        -9.47840439e-04, -9.00440847e-06],
       [ 2.51036648e-05, -5.05186221e-03, -1.18791153e-04,
        -9.28974057e-04, -1.24720221e-05],
       [ 1.58265471e-04, -3.39497435e-03, -1.20200781e-04,
        -7.13855301e-04, -1.11938933e-05],
       [ 1.58059428e-04,  4.51000063e-04, -1.14929752e-04,
        -1.92467839e-04, -5.69187208e-06],
       [ 8.57997863e-05,  3.37595167e-03, -8.43554571e-05,
        -4.34093750e-04, -1.27914566e-05],
       [ 3.33808273e-05,  6.24057857e-03, -4.24396650e-05,
        -8.13177240e-04, -1.05236401e-05],
       [ 2.40541319e-04,  6.68127984e-03, -5.03431502e-05,
         1.14945651e-04, -4.93801930e-06],
       [ 2.54166171e-04,  6.76440055e-03, -1.19864552e-05,
         1.45572188e-03

In [141]:
Beta_Coefficients=pd.Series(classifier.coef_[0])
Beta_Coefficients

0   -0.001403
1   -0.007267
2   -0.000127
3   -0.001292
4   -0.000017
dtype: float64

In [142]:
Coef_df= pd.DataFrame({'Variables': ['balance','duration','campain','days','previous'],
                         'Beta Coefficients': Beta_Coefficients})
Coef_df

Variables  Beta Coefficients
0   balance          -0.001403
1  duration          -0.007267
2   campain          -0.000127
3      days          -0.001292
4  previous          -0.000017

In [143]:
classifier.intercept_

array([-4.00502805e-05, -3.49476841e-05, -3.43765484e-05, -3.19396622e-05,
       -2.95450030e-05, -2.81555668e-05, -1.70661484e-05, -7.20396402e-06,
        1.97371424e-06,  1.20828550e-05,  2.47936282e-05,  3.99918882e-05,
        1.09122323e-04,  1.39832333e-04,  1.44339385e-04,  1.29530561e-04,
        1.29404880e-04,  1.24009954e-04,  1.13027391e-04,  9.72981343e-05,
        6.76806546e-05,  6.80293289e-05,  5.44263203e-05,  4.95519967e-05,
        5.35206694e-05,  4.11682112e-05,  3.86858183e-05,  4.75976232e-05,
        4.69213026e-05,  3.88545023e-05,  2.56978196e-05,  2.91913336e-05,
        2.15106041e-05,  2.14721641e-05,  2.54513408e-05,  1.17218676e-05,
        8.53173366e-06,  9.12344887e-06,  1.17061242e-05,  5.52147286e-06,
       -4.92958011e-06, -8.87525975e-06, -1.47227541e-05, -4.38573560e-05,
       -4.14891026e-05, -4.65574494e-05, -4.54260858e-05, -4.49591260e-05,
       -4.24037605e-05, -4.43050729e-05, -4.65104766e-05, -4.45332430e-05,
       -4.77656449e-05, -

In [144]:
classifier.classes_

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 92, 93, 94, 95])

In [145]:
import numpy as np
np.set_printoptions(suppress=True)
classifier.predict_proba(X)[0:20]

array([[0.00001645, 0.00009798, 0.00030249, ..., 0.00001277, 0.00001165,
        0.00001248],
       [0.00266189, 0.00306797, 0.0034472 , ..., 0.00254691, 0.00246155,
        0.00248366],
       [0.0066012 , 0.00702393, 0.00740663, ..., 0.00646308, 0.00635451,
        0.00638113],
       ...,
       [0.00884691, 0.00947325, 0.0099495 , ..., 0.00871625, 0.008636  ,
        0.0086654 ],
       [0.00104339, 0.00129913, 0.00155068, ..., 0.00097717, 0.00092975,
        0.00094232],
       [0.0082473 , 0.00860954, 0.00893447, ..., 0.00812536, 0.0080284 ,
        0.008052  ]])

In [146]:
classifier.score(X,Y)

0.046493110083829156

In [147]:
#Predictions for X dataset
y_pred = classifier.predict(X)

In [148]:
y_pred

array([32, 32, 32, ..., 32, 32, 32])

In [149]:
y_pred_df= pd.DataFrame({'actual': Y,
                         'predictions': classifier.predict(X)})

In [150]:
y_pred_df[0:30]

actual  predictions
0       58           32
1       44           32
2       33           32
3       47           32
4       33           32
5       35           32
6       28           32
7       42           32
8       58           32
9       43           32
10      41           32
11      29           32
12      53           32
13      58           32
14      57           32
15      51           32
16      45           32
17      57           32
18      60           32
19      33           31
20      28           32
21      56           32
22      32           32
23      25           32
24      40           32
25      44           35
26      39           32
27      52           32
28      46           31
29      36           32

In [169]:

print(len(y_pred_df[y_pred_df['actual']==y_pred_df['predictions']]))
print(len(y_pred_df))

len(y_pred_df[y_pred_df['actual']==y_pred_df['predictions']])/len(y_pred_df)

2102
45211


0.046493110083829156

In [168]:
# Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y,y_pred)
print(cm)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [153]:
TP=len(y_pred_df[(y_pred_df['actual']==1) & (y_pred_df['predictions']==1)])
TN=len(y_pred_df[(y_pred_df['actual']==0) & (y_pred_df['predictions']==0)])
FP=len(y_pred_df[(y_pred_df['actual']==0) & (y_pred_df['predictions']==1)])
FN=len(y_pred_df[(y_pred_df['actual']==1) & (y_pred_df['predictions']==0)])

In [154]:
print('True Positives', TP)
print('True Negatives',TN)
print('False Positives', FP)
print('False Negatives', FN)

True Positives 0
True Negatives 0
False Positives 0
False Negatives 0


In [155]:
#Checking for Accuracy in terms of percentage
((381+395)/(381+197+123+395))*100

70.8029197080292

In [159]:
#Classification report
from sklearn.metrics import classification_report
print(classification_report(Y,y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

          18       0.00      0.00      0.00        12
          19       0.00      0.00      0.00        35
          20       0.00      0.00      0.00        50
          21       0.00      0.00      0.00        79
          22       0.00      0.00      0.00       129
          23       0.00      0.00      0.00       202
          24       0.00      0.00      0.00       302
          25       0.01      0.00      0.00       527
          26       0.00      0.00      0.00       805
          27       0.00      0.00      0.00       909
          28       0.04      0.00      0.00      1038
          29       0.00      0.00      0.00      1185
          30       0.00      0.00      0.00      1757
          31       0.05      0.05      0.05      1996
          32       0.05      0.80      0.09      2085
          33       0.05      0.14      0.08      1972
          34       0.00      0.00      0.00      1930
          35       0.03    